#!/usr/bin/bash
#This scripts takes as input a plink 1 set of files (.bim, .bed, /.fam) and lifts over to a different build. Always do liftover in one step (e.g. hg17-> hg19 instead of hg17-> hg18-> hg19).
#I made this bash script to organize things but the lifting itself uses a script I found here:
#you need this script as well as 
start=`date +%s`
chain=tmp/hg19ToHg38.over.chain.gz #full path to chain file for liftover (downloaded from UCSC)
path_source=to_delete/UKB_EUR_hg38_filt #full path to input file
path_output=to_delete/UKB_EUR_hg19_filt #full path to output file
from=hg19 #build before liftover
to=hg38 #build after liftover
tmp=tmp-dir/ #keep intermediate files here
path_python_script=scripts/liftOverPlink.py #I didn't write this script. I copied it from here: https://github.com/sritchie73/liftOverPlink/blob/master/liftOverPlink.py
#NOTE: that python script was written in python 2 so I made some minor adjustments to make it work for python 3.

plink --bfile ${dt_source} --recode --out ${tmp}genotypes --threads 10 &
wait %1
#Create a "lifted" MAP file.
python scripts/liftOverPlink.py --map ${tmp}genotypes.map --out ${tmp}lifted --chain ${chain} &
wait %1
#Remove bad lifted SNPs from that MAP file.
python scripts/rmBadLifts.py --map lifted.map --out good_lifted.map --log bad_lifted.dat &
wait %1
rm to_exclude.dat
cut -f 2 bad_lifted.dat > to_exclude.dat &
wait %1
cut -f 4 lifted.bed.unlifted | sed "/^#/d" >> to_exclude.dat 
#cut -f 4 lifted.bed.unlifted | sed "/^#/d" >> to_exclude.dat 

# Note: this will clobber the lifted MAP file generated by `liftOverPlink`:
#Generate a good PED file by excluding "unlifted", and bad "lifted" SNPs.
plink --file genotypes --recode --out lifted --exclude to_exclude.dat --threads 15
tr '\r' '\n' < lifted.ped > tmp1 && mv tmp1 lifted.ped
plink --ped lifted.ped --map good_lifted.map --recode --make-bed --out final --threads 15
awk '$5==0' final.bim|cut -f2 > exclude.txt
awk '$5==0' final.bim|cut -f2 >> exclude.txt
sort exclude.txt |uniq > tmp1 && mv tmp1 exclude.txt
#Combine the fixed PED file, with the fixed MAP file.
#conver to .bim/fam/bed
plink --bfile final --exclude exclude.txt --make-bed --out final2 --threads 15 %
wait %1
if [ $dt == 'hrs_eur' -o $dt == 'hrs_afr' -o $dt == 'ukb_chi' ];
then
plink2 --bfile final2 --set-all-var-ids @_\# --make-bed --out to_delete/${dt^^}_${bd2}_test --threads 15
elif [ $dt == 'ukb_eur' -o $dt == 'ukb_afr' ];
then
plink2 --bfile final2 --set-all-var-ids @_\# --make-bed --out to_delete/${dt^^}_${bd2}_filt_test --threads 15
fi

rm genotypes*
rm *lifted*
rm *exclude*
rm final*
